package com.bramgussekloo.projects.dataclasses;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "Model of a buildinginstitute")
public class BuildingInstitute {

    @ApiModelProperty(notes = "Autogenerated id by database", required = false)
    private Integer id;

    @ApiModelProperty(notes = "Id of the building", required = true)
    private Integer buildingId;

    @ApiModelProperty(notes = "Id of the institute", required = true)
    private Integer instituteId;

    public BuildingInstitute(Integer id, Integer buildingId, Integer instituteId) {
        this.id = id;
        this.buildingId = buildingId;
        this.instituteId = instituteId;
    }

    public BuildingInstitute() {
    }

    public Integer getId() {
        return id;
    }

    public Integer getBuildingId() {
        return buildingId;
    }

    public Integer getInstituteId() {
        return instituteId;
    }
}
