package com.bramgussekloo.projects.dataclasses;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "The model of the building")
public class Building {

    @ApiModelProperty(notes = "Autogenerated id of the building", required = false)
    private Integer id;

    @ApiModelProperty(notes = "Id of the address", required = true)
    private Integer address_id;

    @ApiModelProperty(notes = "Name of the building", required = true)
    private String name;

    public Building(Integer id, Integer address_id, String name) {
        this.address_id = address_id;
        this.id = id;
        this.name = name;
    }

    public Building() {
    }

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Integer getAddress_id() {
        return address_id;
    }
}
