package com.bramgussekloo.projects.dataclasses;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "The model of the institute")
public class Institute {

    @ApiModelProperty(notes = "Autogenerated id by the database")
    private Integer id;

    @ApiModelProperty(notes = "Name of the institute")
    private String name;

    public Institute(Integer id, String name){
        this.id = id;
        this.name = name;
    }

    public Institute(){}

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }
}
