package com.bramgussekloo.projects.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Set;

import javax.persistence.*;

@ApiModel(description = "The model of the building")
@Entity
public class Building {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id of the building")
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id")
    @ApiModelProperty(notes = "Id of the address", required = true)
    private Address address;

    @ApiModelProperty(notes = "Name of the building", required = true)
    private String name;

    @ManyToMany(mappedBy = "buildings", fetch = FetchType.LAZY)
    private Set<Institute> institutes;

    public Building(Integer id, Address address, String name) {
        this.address = address;
        this.id = id;
        this.name = name;
    }

    public Building() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
}
