package com.bramgussekloo.projects.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Set;

import javax.persistence.*;

@Entity
@ApiModel(description = "The model of the institute")
public class Institute {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id by the database")
    private Integer id;

    @ApiModelProperty(notes = "Name of the institute")
    private String name;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "BuildingInstitute",
        joinColumns = @JoinColumn(name = "instituteId"),
        inverseJoinColumns = @JoinColumn(name = "buildingId")
    )
    private Set<Building> buildings;

    public Institute(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Institute() {
    }

    public Institute(int id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
